# Generated by Django 5.0.6 on 2024-08-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_groups_user_is_superuser_user_is_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_staff',
        ),
    ]
